server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /tma {
    return 301 /tma/;
  }

  location /tma/ {
    try_files $uri $uri/ /tma/index.html;
  }
}
